### ISSUE TITLE
bug sur les échéances à l'impression

### ISSUE THREAD

**Issue by diablemort** [cfdev/mcercle#14]
Bonjour, d'abord merci pour le logiciel fonctionne à merveille sous linux et Windows, j'ai mis la base sur une Dropbox pour pouvoir travailler de n'importe quels postes.
Bug : Si l'on modifie les dates d'échéances sur les factures, et que l'on enregistre les modifications, il faut fermer la facture puis la rouvrir pour que les modifications soient prises en comptes à l'impression.

**Comment by cfdev** [comment]
Content qu'il fonctionne de cette manière :) avec un google drive ça fonctionne également.
Il faut juste faire gaff au synchro, et faire des sauvegardes de base régulières.
